server.port: 5000

spring:
  jpa:
    #hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    #show-sql: true
 # datasource:
  #  url: jdbc:postgresql://tanakh-project-de.coaocvsxfsex.eu-central-1.rds.amazonaws.com/tanakh_db
   # username: postgres
    #password: gTPBK073vbyo5BYCpTU9sca4BP2q3t0z

hibernate:
  search:
    default:
      directory_provider: filesystem
      indexBase: /data/index/default

apifi.endpoint: /api

sefaria:
  texts-api-base-url: http://www.sefaria.org/api/texts/
  search-api-base-url: http://www.sefaria.org/api/search/text/_search/

aws:
  s3:
    bucket-name: maayan-bucket
    thumbnails-bucket-name: maayan-thumbnails-bucket
