server.port: 5000

spring:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    #show-sql: true

hibernate:
  search:
    default:
      directory_provider: filesystem
      indexBase: /data/index/default

apifi.endpoint: /api

sefaria:
  texts-api-base-url: http://www.sefaria.org/api/texts/
  search-api-base-url: http://www.sefaria.org/api/search/text/_search/

aws:
  s3:
    bucket-name: s3-file-storage-foundationstone

